#!/bin/bash

#change new_receiver.py longtimeout to like 0.4 second

touch difflog.txt

for i in {1..1}; do
    echo $i
	python new_receiver.py &
	proc1=$!
	python new_sender.py
	wait $proc1
	sleep .1
	DIFF=$(diff rcv_file mediumFile.txt) 
	if [ "$DIFF" == "" ] 
	then
	    #echo "The directory was NOT modified"
	    echo 1 >> difflog.txt
	fi
	if [ "$DIFF" != "" ] 
	then
	    #echo "The directory was modified"
	    echo 0 >> difflog.txt
	fi
done
